export default {
  // Common
  Register: 'تسجيل',
  Login: 'تسجيل دخول',
  enter: 'دخول',
  forgetPass: 'نسيت كلمة المرور؟',
  dontHaveAccount: 'ليس لديك حساب؟',
  createNew: ' انشاء جديد',
  password: 'كلمة المرور',
  confirmPassword: 'تأكيد كلمة المرور',
  'forgetPassword?': 'نسيت كلمة المرور؟',
  continue: 'متابعة',
  email: 'البريد الإلكتروني',
  termsOfUse: 'شروط الإستخدام',
  send: 'ارسال',
  phoneNumber: 'رقم الجوال',
  currentPass: 'كلمة المرور الحالية',
  newPass: 'كلمة المرور الجديدة',
  confirmNewPass: 'تأكيد كلمة المرور الجديدة',
  favorites: 'المفضلة',
  cancel: 'إلغاء',

  hello: 'الله يحييك',
  enterPhone: 'أدخل رقم جوالك لاستخدام للتطبيق',
  entrUrPhone: 'أدخل رقم جوالك',

  activationCode: 'رمز التحقق',
  enterCodeSent: 'أدخل رمز التحقق المرسل إلى {{phone}}',
  enterCode: 'أدخل رمز التحقق',
  resendCode: 'إعادة إرسال الرمز',
  sendAfter: 'إعادة إرسال بعد',
  knowHowToMove: 'تعرف على كيفية طلب نقل الإبل عبر التطبيق',
  whereDoUWantToMove: 'أين تريد نقل الإبل؟',
  searchViaLocation: 'ابحث عن الموقع',
  selectFromMap: 'حدد من الخريطة',
  locateArriveLocation: 'تحديد موقع الوصول',
  searchLocation: 'ابحث عن الموقع',
  locateFromMap: 'حدد الموقع من الخريطه',
  setLocation: 'حدد وجهتك',
  confirmMeetingLocation: 'أكد موقع الإلتقاء',
  search: 'إبحث',
  confirmLocation: 'أكّد الوجهة',
  confirmOrder: 'تأكيد الطلب',
  selectVan: 'أختر الشاحنة',
  selectPayment: 'أختر وسيلة الدفع',
  change: 'تغيير',
  startLocation: 'موقع الانطلاق',
  endLocation: 'موقع الوصول',
  searching: 'جاري البحث',
  searchingNow: 'نقوم الآن بالبحث عن أقرب السائقين',
  driverIsOnWayTU: 'السائق في طريقة إليك',
  driverFoundAwayFromU: 'وجدنا سائق يبعد عنك {{time}}',
  call: 'اتصال',
  settings: 'إعدادات',
  SAR: 'ريال',

  technicalSupport: 'الدعم الفني',
  changePhoneNumber: 'تغيير رقم الهاتف',
  commonQuestions: 'الأسئله الشائعة',
  support: 'الدعم',
  termsAndConditions: 'الشروط والأحكام',
  privacyPolicy: 'سياسه الخصوصية',
  signOut: 'تسجيل الخروج',
  otherLinks: 'روابط أخرى',
  edit: 'تعديل',
  youHaveQuestion: 'هل لديك سؤال؟ نحن هنا لمساعدتك',
  weHereToHelp: 'نحن هنا لمساعدتك على مدار اليوم',
  PreviousOrders: 'الطلبات السابقة',
  main: 'الرئيسية',
  profile: 'الملف الشخصي',
  fullName: 'الإسم كاملا',
  typePhone: 'أدخل رقم جوالك',
  messageContent: 'نص الرسالة',
  weCantMove: 'لا يمكننا نقل الابل لهذا المكان رجاء قم بتغيير الوجهة',

  worngOtp: 'كود التفعيل غير صحيح',
  invalidSudiNumber: 'رجاء قم بادخال رقم هاتف صحيح',
  selectPickUp: 'يجب عليك تحديد وجهتك',
  selectDropOff: 'يجب عليك تحديد موقع الإلتقاء',
};
